[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --port /dev/ttyACM0"

[env]
ESP_LOG="info"
# WiFi Configuration (update with your values)
WIFI_SSID="ssid"
WIFI_PASSWORD="top-secret"
BACKEND_URL="https://arewegoneyet.xn--viitamki-5za.fi/api/destroy"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
