[package]
name = "firmware"
version = "0.1.0"
authors = ["Mikko Viitamäki <mikko.vitamaki@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-hal = { version = "1.0.0", features = ["esp32c6", "unstable"] }
esp-backtrace = { version = "0.14.2", features = ["esp32c6", "panic-handler", "println"] }
esp-println = { version = "0.12.0", features = ["esp32c6", "log"] }
log = { version = "0.4.22" }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32c6"] }
esp-hal-smartled = { version = "0.17.0" }
smart-leds = { version = "0.4.0" }

# WiFi and networking
# TODO: Add back when WiFi dependencies are resolved
# esp-alloc = { version = "0.9.0" }
# TODO: Find compatible version of esp-wifi for esp-hal 1.0.0
# esp-wifi = { git = "https://github.com/esp-rs/esp-wifi.git", features = ["esp32c6", "wifi"] }
# smoltcp = { version = "0.11.0", default-features = false, features = [
#     "medium-ethernet",
#     "proto-dhcpv4",
#     "proto-ipv4",
#     "socket-dhcpv4",
#     "socket-tcp",
# ] }
# blocking-network-stack = { git = "https://github.com/bjoernQ/blocking-network-stack.git", rev = "b3ecefc222d8806edd221f266999ca339c52d34e", default-features = false, features = ["dhcpv4", "tcp"] }
# heapless = { version = "0.8", default-features = false }
